### ISSUE TITLE
config ActiveDataProvider db

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/yii-dataview#11]
### What steps will reproduce the problem?
Config ActiveDataProvider db

### Error Mesage
`Argument 1 passed to yii\activerecord\data\ActiveDataProvider::__construct() must implement interface yii\db\ConnectionInterface`

### Additional info
How to configure the connection of the db with ActiveDataProvider.

| Q                | A
| ---------------- | ---
| Yii version      | 3.0
| PHP version      |  7.2.14
| Operating system | Centos 7

**Comment by machour** [comment]
I don't think it's up to yii-dataview to config the `db` parameter.
If you intend to use ActiveDataProvider, then you're supposed to have your db configured in your app.

**Comment by terabytesoftw** [comment]
Of course I have it configured and working but dataview does not take the value of the connection, try to pass the value directly but it has several errors.

**Comment by machour** [comment]
How do you create your provider? Can you show some code?

**Comment by terabytesoftw** [comment]
Very simple:

```
$dataProvider = new ActiveDataProvider([
    'query' => User::find(),
]);
```

**Comment by FabrizioCaldarelli** [comment]
@terabytesoftw ActiveDataProvider needs constructor parameters:

```php
$db = Yii::$app->db;
$query = User::find();
$dataProvider = new ActiveDataProvider( $db, $query );
```

**Comment by terabytesoftw** [comment]
It worked perfect, you have to put it in the documentation,

Thks.

**Comment by FabrizioCaldarelli** [comment]
I've updated the doc and added an issue about ActiveDataProvider constructor parameters:

https://github.com/yiisoft/active-record/issues/38
https://github.com/yiisoft/active-record/pull/39
