### ISSUE TITLE
Doesn't translate messages

### ISSUE THREAD

**Issue by kratkar** [yiisoft/yii-dataview#123]
I think in di.php incorrect 'tags'(need 'translation.categorySource'?)

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 3
| PHP version      | 8.2

**Comment by samdark** [comment]
Yes. Likely. Would you please try?

**Comment by kratkar** [comment]
Yes, I tried. After changed it worked

**Comment by terabytesoftw** [comment]
https://github.com/yiisoft/yii-dataview/blob/master/tests/GridView/TranslatorTest.php

**Comment by samdark** [comment]
@terabytesoftw I see that tests are using different container config than what's in config, right? Maybe that's the issue?

**Comment by vjik** [comment]
Done by #132
