### ISSUE TITLE
Incorrect last page link

### ISSUE THREAD

**Issue by kratkar** [yiisoft/yii-dataview#129]
Hi!
In [$items[] = $this->renderLastPageNavLink($currentPage, $endPage);](https://github.com/yiisoft/yii-dataview/blob/90895a9efcf2a81ad710bf47171e9edd3fd2164a/src/OffsetPagination.php#L210C33-L210C48) maybe need to use $totalPages instead of $endPage?

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 3
| PHP version      | 8.1
| Operating system | Ubuntu 22

**Comment by vjik** [comment]
Already fixed.
