### ISSUE TITLE
GridView causes 500 error

### ISSUE THREAD

**Issue by GHopperMSK** [yiisoft/yii-dataview#13]
I think it is about configuration. When I add GridView on page, I got `500 Internal Server Error`.

### What steps will reproduce the problem?

`php composer.phar require yiisoft/yii-dataview`

vendor/yiisoft/yii-base-web/src/controllers/SiteController.php
```
public function actionAbout()
{
    $array = [
        ['id' => 1, 'file' => '1.txt', 'name' => '1'],
        ['id' => 2, 'file' => '2.txt', 'name' => '2'],
    ];

    $dataProvider = new \yii\data\ArrayDataProvider([
        'allModels' => $array,
        'pagination' => [
            'pageSize' => 10,
        ],
    ]);

    return $this->render('about', ['provider' => $dataProvider]);
}
```

vendor/yiisoft/yii-base-web/src/views/site/about.php
```
...
<?=
\yii\dataview\GridView::widget([
    'dataProvider' => $provider,
    'columns' => [
        'id',
        'name',
        'file',
    ],
]);
?>
```

### What is the expected result?

GridView with the data

### What do you get instead?

An internal server error occurred.

### Additional info

`vendor/yiisoft/yii-core/src/data/BaseDataProvider::__construct($id = null)` gets config array as $id. As result, any statement like `$this->id . '-page';` throws error `Array to string conversion`. I changed input config:
```
$dataProvider = new \yii\data\ArrayDataProvider([
    'key' => 'id',
    'allModels' => $array,
    'pagination' => [
        'pageSize' => 10,
    ],
]);
```
and replace all `$this->id . ` to `$this->id['key'] .`. After that the error is gone but table renders without any content in it (only header).

I do something wrong, but what exactly?

| Q                | A
| ---------------- | ---
| Yii version      | 3.0
| PHP version      | 7.2.15
| Operating system | Ubuntu

**Comment by terabytesoftw** [comment]
Review https://github.com/yiisoft/active-record/blob/master/src/data/ActiveDataProvider.php phpdocs
