### ISSUE TITLE
ListView and semantics

### ISSUE THREAD

**Issue by sjaakp** [yiisoft/yii-dataview#14]
In an attempt to write semantical correct HTML I used a `ListView` with:

`        'options' => [ 'tag' => 'ol' ],
        'itemOptions' => [ 'tag' => 'li' ]
`

However, I learned that the summary and the pager appeared inside the OL, like a kind of list items, which they are certainly not. 

Of course, there are ways to work around this, such as overriding `renderItems()`, but it occurs to me that there must be a simpler way to get a semantical correct list out of `ListView`.

Perhaps something to consider for Yii3?

**Comment by glpzzz** [comment]
Hello, I just notice I have a WIP about this https://github.com/yiisoft/yii-dataview/issues/14. Just the changes on tests required to finish. 

Is this something worth working on?

**Comment by vjik** [comment]
I like this suggestion

**Comment by samdark** [comment]
> Is this something worth working on? 

Yes, please do.

**Comment by vjik** [comment]
@glpzzz Any news? Maybe you need help?

**Comment by glpzzz** [comment]
Starting today I have some available days.
