### ISSUE TITLE
Undefined property: App\Invoice\Entity\Inv Cycle ORM Proxy::$id

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/yii-dataview#140]
### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 8.2
| Operating system | Windows 11

..resources/view/invoice/inv/index.php
````
<?php
    $read_with_iterable_type = $paginator_with_readabledatainterface_type->read();
    /**
     * @var ColumnInterface[] $columns
     */
    $columns = [
          new DataColumn(
              'id'
          )   
    ];
?>
<?php  echo GridView::widget()
    // unpack the contents within the array using the three dot splat operator    
    ->columns(...$columns)
    ->dataReader($paginator_with_readabledatainterface_type)    
?>
````
Hi Vijk,
If I pass an empty array for $columns, the GridView attempts to build the ActionColumns ie. view etc and  I get the following error as well:

![image](https://github.com/yiisoft/yii-dataview/assets/8538339/9d2468b0-5c31-43c2-b356-6f1cc3a5e9e9)

I thought this might be of interest.  The code appears not to be accepting the DataColumn's first argument id because it has no property type associated with it ie. undefined property.  This appears to be a Cycle issue.

**Comment by vjik** [comment]
Thanks for report 👍

**Comment by rossaddison** [comment]
No probs Vijk. Keep up the hard development work. You are making amazing contributions to the Php community.

**Comment by vjik** [comment]
@rossaddison I updated package, can you try now?

**Comment by vjik** [comment]
Hm. Does entity contain property `id`? Or used `getId()`?

**Comment by vjik** [comment]
I understand. Now `GridView` getting value from object property, but in your case need to use getter.

But do this cycle entry work with Yii3 GridView before?

**Comment by rossaddison** [comment]
Yes the cycle entity was working with the Yii3 GridView before.

**Comment by vjik** [comment]
> Yes the cycle entity was working with the Yii3 GridView before.

Hm. It's very strange, because getting of value not changed...

**Comment by rossaddison** [comment]
I have noticed the yiisoft/form has changed and I have static errors. I am going to fix these first and test. I will get back to you.

**Comment by vjik** [comment]
Oh. Seems, I understand.

Instead of this code:

```php
DataColumn::create()
	->attribute('id')
	->label($s->trans('id'))
	->value(),
```

Try it:

```php
new DataColumn(
	'id',
	header: $s->trans('id'),
	content: static fn(object $any) => $any->getId()
);
```

**Comment by vjik** [comment]
> I have noticed the yiisoft/form has changed and I have static errors. I am going to fix these first and test. I will get back to you.

Now I am actively working on Yii Form and Yii DataView, changes with break BC are possible :( But I hope, result will be good.
