### ISSUE TITLE
GridView - can't set css class on tbody when empty rows

### ISSUE THREAD

**Issue by uaoleg** [yiisoft/yii-dataview#16]
### `emptyTextOptions` should be assigned to the `tbody` instead of `div` inside it

![empty](https://user-images.githubusercontent.com/1773775/32212317-fef4137e-be1e-11e7-81ea-22364e73c664.jpg)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.0
| Operating system | Windows

**Comment by samdark** [comment]
Works alright in current `master`.

**Comment by samdark** [comment]
See https://github.com/yiisoft/yii-dataview/blob/master/src/GridView.php#L634
