### ISSUE TITLE
GridView empty column options

### ISSUE THREAD

**Issue by khotim** [yiisoft/yii-dataview#17]
The current available options for GridView empty column are `$emptyCell`, `$emptyText`, and `$emptyTextOptions.`
Is there any configuration like `$emptyColumnOptions` or similar function ?

From yii\grid\Gridview source line 489:
`return "<tbody>\n<tr><td colspan=\"$colspan\">" . $this->renderEmpty() . "</td></tr>\n</tbody>";`

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12

**Comment by samdark** [comment]
Closing since it seems to be quite rare case.
