### ISSUE TITLE
In OffsetPagination, no way of setting private member variables $labelPrevious, $labelNext, $labelFirst, $labelLast

### ISSUE THREAD

**Issue by aphraoh** [yiisoft/yii-dataview#177]
### What steps will reproduce the problem?
In OffsetPagination no way of setting private member variables below...
`private string|Stringable|null $labelPrevious = 'âŸ¨';`
`private string|Stringable|null $labelNext = 'âŸ©';`
`private string|Stringable|null $labelFirst = 'âŸª';`
`private string|Stringable|null $labelLast = 'âŸ«';`

### What is the expected result?
Would expect public member functions below...
`public function labelPrevious(string|Stringable|null $labelPrevious): self {$new=clone $this;$new->labelPrevious=$labelPrevious;return $new;}`
`public function labelNext    (string|Stringable|null $labelNext):     self {$new=clone $this;$new->labelNext=$labelNext;        return $new;}`
`public function labelFirst   (string|Stringable|null $labelFirst):    self {$new=clone $this;$new->labelFirst=$labelFirst;      return $new;}`
`public function labelLast    (string|Stringable|null $labelLast):     self {$new=clone $this;$new->labelLast=$labelLast;        return $new;}`

You can then do something like this...
`$pagination = (new OffsetPagination())`
`->paginator($paginator)`
`->labelPrevious(NoEncode::string('<i class="fas fa-play fa-rotate-180"></i>'))`
`->labelNext(NoEncode::string('<i class="fas fa-play"></i>'))`
`->labelFirst(null)`
`->labelLast(null);`

### What do you get instead?
Instead you are stuck with the default setting.

### Additional info
@vjik if you find this code change exceptable, I can do change and submit pull request.

| Q                | A
| ---------------- | ---
| Version          | master
| PHP version      | 8
| Operating system | Window/Linux

**Comment by vjik** [comment]
@aphraoh Yes, this good suggestion.

**Comment by aphraoh** [comment]
@vjik , done, please see pull request https://github.com/yiisoft/yii-dataview/pull/178

**Comment by vjik** [comment]
Done by #178
