### ISSUE TITLE
Add `pageSizeConstraint` option to `BaseListView`

### ISSUE THREAD

**Issue by vjik** [yiisoft/yii-dataview#218]
Available values: 
- `true` (deny to change page size, default)
- `false` (allow any page size)
- `int` (maximum page size value)
- `list<int>` (list of available page size values)

Also need UI-element for change page size similar to pagination.

**Comment by samdark** [comment]
@vjik implemented the constraint check. Not sure about how UI should look like.

**Comment by vjik** [comment]
> @vjik implemented the constraint check. Not sure about how UI should look like.

UI needs when constraint is array. I think, it should be dropdown element (`<select>`).

**Comment by samdark** [comment]
So about UI:

- true — nothing should be displayed
- false — positive int input
- number - positive int input limited by the number provided
- list<int> - dropdown with pre-defined int values
