### ISSUE TITLE
Class 'yii\widgets\Widget' not found

### ISSUE THREAD

**Issue by iqbalhs** [yiisoft/yii-dataview#24]
I was trying to get this installed in my `yii-demo`, but it failed when initiating the object as it's not able to find class `yii\widgets\Widget`.
Did i miss something or are there dependency errors.

### What steps will reproduce the problem?
Install `yiisoft/yii-demo` with composer create project
Require `yiisoft/yii-dataview`

### What is the expected result?
Able to use widgets provided in this package.

### What do you get instead?
Got an error message `Class 'yii\widgets\Widget' not found` when trying to initiate the widget.

### Additional info

| Q                | A
| ---------------- | ---
| Version          | dev
| PHP version      | 7.3.6
| Operating system | Windows 10

**Comment by samdark** [comment]
Yes, it's not ready.
