### ISSUE TITLE
LinkPager loose main css class before is defined

### ISSUE THREAD

**Issue by Eseperio** [yiisoft/yii-dataview#27]
### What steps will reproduce the problem?
Create a LinkPager widget and set only the "options" key with an empty array as value. 
`echo LinkPager::widget([
       'pagination' => $pages,
      'options'=>[
      ]
   ]);`
### What is the expected result?
Should keep "pagination" css class.
### What do you get instead?
It looses its css class.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version    | 5.5.3 
| Operating system |OSX

**Comment by samdark** [comment]
Not applicable to Yii3.
