### ISSUE TITLE
Pagination: page attribute, wrong count.

### ISSUE THREAD

**Issue by Portaflex** [yiisoft/yii-dataview#29]
I want to keep page for pagination in GridView. So I use Yii::$app->session.
But the page for the pagination component is not the actual saved page value but, instead, that value minus one. Why?

### What steps will reproduce the problem?
```
function search ()
    {
        if ($data = Yii::$app->request->get()) Yii::$app->session['cita_params'] = $data;
        $params = Yii::$app->session['cita_params'];
        $query = self::v_cita();
        $dataProvider = new ActiveDataProvider([
        		'query' => $query,
        		'pagination' => [
        		    'pageSize' => 30,
        		    'page' => $params['page'] - 1
        		],
        ]);
```

### What is the expected result?

I should be able to use just the saved page number.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 5.6
| Operating system |Linux Mint Debian edition

**Comment by samdark** [comment]
Page number is used in yiisoft/data: https://github.com/yiisoft/data/?tab=readme-ov-file#offset-pagination
