### ISSUE TITLE
Should ListView/GridView return to first page when sort changes

### ISSUE THREAD

**Issue by Sammaye** [yiisoft/yii-dataview#3]
I have noticed that I can be on page 3 of ListView but when I change the sort it remains on page 3. Logically you would expect it to return to page 1 since page 3 of a new sort is not very useful to the end user.

Should it be changed to go from page 1 when sort changes?

**Comment by nutfergie** [comment]
```
        $(document).on('pjax:success', function() {
             $('#grid_id th a').attr('href', function(i,data){
                 return  data.replace( /&page=[0-9]/gi, '' );        
      });

```

I solve it via jquery

**Comment by vjik** [comment]
Currently, we can use `GridView` method `keepPageOnSort()` to configure it. By default page don't keep on sort changing.
