### ISSUE TITLE
ListView summary tag not used if custom summary is supplied

### ISSUE THREAD

**Issue by francisberesford** [yiisoft/yii-dataview#4]
Could be related to #2460

If you define a custom summary for list view the containing wrapper tag (default is div)  is not rendered, making summaryOptions useless. We can add our div to the summary option like this as a workaround

`'summary' => '<div class="summary">Showing ...'`

But I don't think that's what's intended is it?

**Comment by samdark** [comment]
Not applicable to Yii3.
