### ISSUE TITLE
Missing encode(false) in GridView::renderColumnGroup

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/yii-dataview#62]
When i using GridView options like this
`
[
                'class' => ***,
                'options()' => [
                    [
                        'style' => [
                            'width' => '200px'
                        ]
                    ]
                ]
            ]
`

it render that encoded output

`&lt;col style="width: 200px;"&gt;
  | &lt;col style="width: 200px;"&gt;
  | &lt;col style="width: auto;"&gt;`

To fix it need add `encode(false)` to colgroup render in `renderColumnGroup` method

**Comment by samdark** [comment]
@terabytesoftw would you please take a look?
