### ISSUE TITLE
Yiisoft\Router\FastRoute\UrlMatcher вызывает несуществующий метод в LinkPager

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/yii-dataview#63]
При попытке подключить пагинацию в GridView (и наверно в других dataview виджетах) происходит следующая ошибка

`Call to undefined method Yiisoft\Router\FastRoute\UrlMatcher::getCurrentRoute()`

![2021-09-17 19 03 57 localhost 1e7c18e27439](https://user-images.githubusercontent.com/90403480/133819626-e9539bf7-5e96-4f76-9951-1f7272e21a86.jpg)

**Comment by terabytesoftw** [comment]
You can check if the changes solve the problem,

Thks.

**Comment by Gerych1984** [comment]
> You can check if the changes solve the problem,
> 
> Thks.

Yes, now it's works, but i have are question - i can set OffsetPaginator::$currentPage only manual? Thx
