### ISSUE TITLE
Query limit not working with pager enabled.

### ISSUE THREAD

**Issue by skworden** [yiisoft/yii-dataview#7]
The pagerination pageSize overrides the limit set in the query

```
$query = Objects::find()->orderBy('name ASC')->limit(50);
        $dataProvider = new ActiveDataProvider([
                'query' => $query,
                'pagination' => array('pageSize' =>24)
        ]);
```

The above produces

```
find.count({"ns":"geekobjects.objects","limit":-1,"batchSize":0,"skip":-1,"flags":0,"query":{},"fields":[],"started_iterating":false})

```

Which in turns overrides the limit of 50 and returns all of the collections instead of 50

```
$query = Objects::find()->orderBy('name ASC')->limit(50);
        $dataProvider = new ActiveDataProvider([
                'query' => $query,
                'pagination' => false
        ]);
```

the above produces

```
find({"ns":"geekobjects.objects","limit":50,"batchSize":0,"skip":0,"flags":0,"query":{"$query":{},"$orderby":{"name":1}},"fields":[],"started_iterating":false})
```

which limits the query to 50 items but now there isn't a pager since it was set to false.

I don't know if it was intended to do this / or if this is a bug / or if I'm not doing this correctly.

**Comment by samdark** [comment]
Not applicable to Yii3.

**Comment by samdark** [comment]
Valid use case.

**Comment by vjik** [comment]
Note. When passed data reader with limit to grid view with allowed sorting, need throw logic exception.

**Comment by samdark** [comment]
Closing, since there's no need to implement it in this package. It is `yiisoft/data` entirely.

**Comment by samdark** [comment]
Still need a check. If data reader has limit then sorting should be disabled.

**Comment by vjik** [comment]
> Still need a check. If data reader has limit then sorting should be disabled.

Maybe it's better to throw logic exception, so developer should change own code?

**Comment by samdark** [comment]
Grid without sorting does make sense so I don't think throwing an exception is a good idea.

**Comment by vjik** [comment]
> Grid without sorting does make sense so I don't think throwing an exception is a good idea.

Throw exception when data reader has limit and sorting enabled in grid view only. When sorting disabled don't throw exception.

**Comment by samdark** [comment]
Makes sense.
