### ISSUE TITLE
Customizable/extendable column format parsing

### ISSUE THREAD

**Issue by BLumia** [yiisoft/yii-dataview#81]
This is a feature request.

Right now we can use `"attribute:format:label"` to describe the display rule of a column in [GridView](https://github.com/yiisoft/yii-dataview/blob/9886579061e5d3bbe1d0bf8de82079f065021f31/src/GridView.php#L454-L459) and [DetailView](https://github.com/yiisoft/yii-dataview/blob/316dcebd9db1a0832df3335cac1c505f7f5e77b9/src/DetailView.php#L281-L286), `format` declared the formatter to use. Developers can create their own custom formatter class by extending `\yii\i18n\Formatter` to add custom formatters to fit their needs. Sometimes developers may need to add some extra argument to a formatter to get more flexible control, then we'll need to create an array with a `'format'` key instead to pass arguments to the formatter:

``` php
// for example:
// from
	'testAttr:example:Test Attr',
// to
	[
		'attribute' => 'testAttr',
		'label' => 'Test Attr',
		'format' = ['example', false],
	]
```

As a possible solution, I think using something like `attribute:format(arg1,arg2):label` to define the column display format could be handy, so as long as the arguments are not complex, developers won't need to stop and do the manual convert, so developers could keep focus on what they need to implement. I did a sample implementation to parse such format:

<details>
Example format string:

- `'testAttr:example:Test Attr'`
- `'testAttr:example(true):Test Attr'`
- `'testAttr:example(true,false,"string",114514):Test Attr'`

Sample implementation for Yii2 GridView

DataColumnTrait.php

``` php
<?php

namespace backend\traits;

use yii;
use yii\helpers\Html;
use yii\base\InvalidConfigException;
use yii\grid\DataColumn;

trait DataColumnTrait
{
/**
     * Creates a [[DataColumn]] object based on a string in the format of "attribute:format:label".
     * @param string $text the column specification string
     * @return DataColumn the column instance
     * @throws InvalidConfigException if the column specification is invalid
     */
    protected function createDataColumn($text)
    {
        if (!preg_match('/^([^:]+)(:(\w*)(\([\w,+_"]*\))?)?(:(.*))?$/', $text, $matches)) {
            throw new InvalidConfigException('The column must be specified in the format of "attribute", "attribute:format" or "attribute:format:label"');
        }

        $formatArr = [
            isset($matches[3]) ? $matches[3] : 'text'
        ];

        if (isset($matches[4])) {
            $args = array_filter(explode(',', substr(trim($matches[4]), 1, -1)));
            foreach ($args as $arg) {
                // if (empty($arg)) continue;
                $arg = trim($arg);
                if ($arg[0] == '"') {
                    $actualVal = str_replace('"', '', $arg[0]);
                    array_push($formatArr, $actualVal);
                } elseif (is_numeric($arg)) {
                    array_push($formatArr, intval($arg));
                } elseif (in_array($arg, ["false", "true"])) {
                    array_push($formatArr, $arg == "true");
                } else {
                    throw new InvalidConfigException('Unrecognized argument(s), supported argument type are: true, false, digits(number) and double-quoteed string. Use comma to split multiple arguments');
                }
            }
        }

        return Yii::createObject([
            'class' => $this->dataColumnClass ?: DataColumn::class,
            'grid' => $this,
            'attribute' => $matches[1],
            'format' => $formatArr,
            'label' => isset($matches[6]) ? $matches[6] : null,
        ]);
    }
}
```

GridView.php

``` php
<?php

namespace backend\components;

use backend\traits\DataColumnTrait;

class GridView extends \yii\grid\GridView
{
    use DataColumnTrait;
}
```

</details>

But by looking into the implementation from the Yii codebase, it seems the logic of parsing that format string is live in different places and not as extendable as using a custom formatter, so I suggest we could make such thing extendable by extracting that part of logic and allow developer use their own *"ColumnFactory"* (example name) or make these `*View` use the same `trait` to do the column format parse job.

**Comment by samdark** [comment]
There's no short format anymore, `ColumnInterface` is used.
